services:
  app:
    build: .
    container_name: coding-talk-app
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/coding-talk
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=minschive
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/coding-talk

  mysql:
    image: mysql:8.0
    container_name: coding-talk-mysql
    environment:
      MYSQL_ROOT_PASSWORD: minschive
      MYSQL_DATABASE: coding-talk
    ports:
      - "3305:3306"
    volumes:
      - mysql-data:/var/lib/mysql


  mongodb:
    image: mongo:latest
    container_name: coding-talk-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mysql-data:
  mongo-data:
